name: crowdin-download-pr workflow
on:
  workflow_dispatch:

jobs:
  crw-dwn-pr-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Induce Build
        id: induce-build
        uses: satak/webrequest-action@master
        with:
          url: https://api.crowdin.com/api/v2/projects/483057/translations/builds
          method: POST
          headers: '{"Authorization": "Bearer ${{ secrets.CROWDIN_PERSONAL_TOKEN }}"}'
          payload: '{}'

      - name: Get data
        id: vars 
        run: echo ::set-output name=outputvar::$(echo '${{ steps.induce-build.outputs.output }}' | jq '.data.data')
      - name: Print data
        run: |
           chmod +x ../../crowdin/crowdin_init.sh
           ../../crowdin/crowdin_init.sh
        shell: bash
#          echo ${{ steps.vars.outputs.outputvar }}
