name: crowdin-download-pr workflow
on:
  workflow_dispatch:

jobs:
  crw-dwn-pr-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: yq - portable yaml processor
        uses: mikefarah/yq@v4.13.5

      - name: Run Scripts
        shell: bash
        working-directory: crowdin
        run: |
          cd ./js && npm install && cd ..
          node js/index.js ${{ secrets.CROWDIN_PROJECT_ID }} ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

#       - name: Induce Build
#         id: induce-build
#         uses: satak/webrequest-action@master
#         with:
#           url: https://api.crowdin.com/api/v2/projects/483057/translations/builds
#           method: POST
#           headers: '{"Authorization": "Bearer ${{ secrets.CROWDIN_PERSONAL_TOKEN }}"}'
#           payload: '{}'

#       - name: Get data
#         id: vars 
#         run: echo ::set-output name=outputvar::$(echo '${{ steps.induce-build.outputs.output }}' | jq '.data.data')

      # - name: Script data
      #   shell: bash
      #   working-directory: crowdin
      #   run: |
      #      chmod +x crowdin_init.sh
      #      ./crowdin_init.sh ${{ secrets.CROWDIN_PROJECT_ID }} ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Yaml Changes
          title: Update YAML FILEs
          body: Testing Yaml Files
          branch: yml-updates
#          echo ${{ steps.vars.outputs.outputvar }}
