name: YAML workflow
on:
  push:
    branches: [ main ]
    paths:
      - 'locales-yml/en.yml'
  
  workflow_dispatch:

jobs:
  yml-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v10

      - name: crowdin action
        uses: crowdin/github-action@1.4.0
        with:
          upload_sources: true
          download_translations: true
          localization_branch_name: 'translations_branch'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
