name: PR Create workflow
on:  
  workflow_dispatch:

jobs:
  pr-create-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Update AUTHORS
        run: |
          git rev-parse --show-toplevel
#       - name: Create Pull Request
#         uses: peter-evans/create-pull-request@v3
#         with:
#           commit-message: update authors
#           title: Update AUTHORS
#           body: Credit new contributors by updating AUTHORS
#           branch: update-authors
