name: yaml file workflow
on:
  push:
    branches: [ master ]
    paths:
    - 'locales-yml/en.yml'
  
  workflow_dispatch:

jobs:
  yml-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: yq - portable yaml processor
        uses: mikefarah/yq@v4.13.5

      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Set HEAD SHA
        id: head-sha
        run: echo "::set-output name=sha::$(git rev-parse HEAD)"
        
      - name: Print yaml key
#         working-directory: locales-yml
        run: |
          git show ${{ github.sha }}:locales-yml/en.yml > pr-en.yml
          yq eval -o=j pr-en.yml > yml-to-json.json
          jq -r '[leaf_paths as $path | {"key": $path | join("."), "value": getpath($path)}] | from_entries' yml-to-json.json > pr-en.json
          git checkout ${{ github.event.before }}
          yq eval -o=j locales-yml/en.yml > orig-to-json.json
          jq -r '[leaf_paths as $path | {"key": $path | join("."), "value": getpath($path)}] | from_entries' orig-to-json.json > orig-en.json
        
      - name: Upload git diff artifact
        uses: actions/upload-artifact@v2
        with:
          name: ymltojson
          path: pr-en.json

      - name: Upload git diff artifact
        uses: actions/upload-artifact@v2
        with:
          name: originaljson
          path: orig-en.json
#         run: cat test.yml | yq e '.en.time.am'
#         run: echo {{ yq e '.en.time.am' ../locales-json/en.yaml }}
          # jq -r '[paths | join(".")]' yml-to-json.json > pr-en.json

